import 'jquery';
import '@govuk/angularjs-devtools';
import 'angular';
import 'angular-ui-bootstrap';
import 'angular-ui-router';
import 'angular-animate';
import 'angular-breadcrumb';
import 'angular-sanitize';
import 'prismjs';
import 'ngSmoothScroll';
import 'ng-clamp';

// Angular2
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/router';
import '@angular/upgrade';
